config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "photos#index"
  resources :photos, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'dComplete'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:account_name])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.order("created_at DESC")
  end
  
  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.valid?
      @photo.save
      redirect_to root_path
    else
      render new_photo_path
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    if user_signed_in? && @photo.user_id == current_user.id
      @photo.destroy
      redirect_to dComplete_photos_path
    else
      render acction: :show
    end
  end

  def dComplete
  end

  private
  def photo_params
    params.require(:photo).permit(:image, :title, :explanation).merge(user_id: current_user.id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PhotoExhibition
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href =>"https://fonts.googleapis.com/css?family=Lexend+Deca|Sawarabi+Gothic&display=swap", :rel => "stylesheet"}/
  %body
    = yield

app/views/photos/_photo-error-messages.haml
- if user.errors.any?
  - unless user.valid?
    - if errors = user.errors.full_messages_for(column.to_sym)
      %ul
        - errors.each do |error|
          %li.user-error-messages-signup=error

:css
  .user-error-messages-signup{
    color: #ea352d;
    margin: 5px auto 20px;
    font-size: 15px;
  }
  .icon {
  border-color: #ea352d;
  }

app/views/photos/_photo.html.haml
.photo
  = link_to image_tag(photo.image.url, class: "image"), photo_path(photo.id)

app/views/photos/dComplete.html.haml
.complete
  .complete__box
    .complete__box__message
      削除が完了しました

  
    .complete__box__btn
      = link_to root_path, class: "link_btn" do
        .complete__box__btn__text
          TOPページに戻る

app/views/photos/index.html.haml
.wrapper
  = render "shared/header"

  .main
    %p.main__title
      ENGRAVED MEMORIES

    .main-contets
      .photo-title
        POSTS
      .photos
        = render @photos


  = render "shared/footer"

app/views/photos/new.html.haml
= render "shared/header"
.content
  NEW POST
= form_for @photo do |f|
  .field
    アイコンをクリックして写真を選択
    %br/
    = f.label :image, class: 'input' do
      = fa_icon 'picture-o', class: 'icon'
      = f.file_field :image, class: 'hidden', accept: "image/*"
      = render partial: '/photos/photo-error-messages', locals: {user: @photo, column: "image"}
    %br/
  .field
    タイトル
    %br/
    = f.text_field :title, class: 'input', placeholder: '(例）写真旅', maxlength: "20"
    = render partial: '/photos/photo-error-messages', locals: {user: @photo, column: "title"}
  .field
    詳細
    %br/
    = f.text_area :explanation, class: 'input-explanation', placeholder: '写真の思い出を書いてください'
  .actions
    = f.submit '投稿', class: 'new-post-submit-btn'

app/views/photos/show.html.haml
= render "shared/header"
.content
  .show-photo
    = image_tag @photo.image.url, class: "show-image"
  .show-title
    = @photo.title
  .show-explanation
    %p= @photo.explanation
  - if user_signed_in? && @photo.user_id == current_user.id
    .show-photo-btn
      = link_to  "/photos/#{@photo.id}", class: "link_btn", method: :delete do
        .show-photo-btn__text
          写真を削除する
= render "shared/footer"

app/views/shared/_footer.html.haml
.footer
  .footer__box
    %ul.f-manus
      - if user_signed_in?
        %li.f-menu
          = link_to 'POST', new_photo_path, class: 'link_tag'
        %li.f-menu
          = link_to 'LOGOUT',  destroy_user_session_path, method: :delete, class: 'link_tag'
      - else
        %li.f-menu
          = link_to 'LOGIN',  user_session_path, method: :post, class: 'link_tag'
        %li.f-menu
          = link_to 'NEW ACCOUNT',  new_user_registration_path, class: 'link_tag'
    %p.footer__box__copy
      © PHOTO EXHIBITION
  %ul.footer__lists
    %li.list
      = link_to "https://twitter.com/" do
        = fa_icon 'twitter', class: 'icon'
    %li.list
      = link_to "https://www.instagram.com/" do
        = fa_icon 'instagram', class: 'icon'
    %li.list
      = link_to "https://www.facebook.com/" do
        = fa_icon 'facebook-f', class: 'icon'

app/views/shared/_header.html.haml
.header
  .logo
    = link_to 'PHOTO EXHIBITION', root_path, class: 'link_tag'
  %ul.h-menus
    - if user_signed_in?
      %li.account_name
        = current_user.account_name
      %li
        = link_to destroy_user_session_path, method: :delete, class: 'link_tag' do
          .h-menu
            LOGOUT
      %li
        = link_to new_photo_path, class: 'link_tag' do
          .h-menu
            POST
    - else
      %li
        = link_to new_user_registration_path, class: 'link_tag' do
          .h-menu
            NEW ACCOUNT
      %li
        = link_to user_session_path, method: :post, class: 'link_tag' do
          .h-menu
            LOGIN